Repository xpotify/xpotify, pull requests merged in 2025-03, with the labels that each got.

#41 Updating /dev branch with security update @master
  package-lock.json
Labels: dependencies

#44 Fix Issue #I.23 & Updating Test Data @ recentTracks
  server/public/script/sectionsv2.js
  server/views/v2.ejs
Labels: bug, enhancement, Test Data

#45 Update README.md
  README.md
Labels: enhancement

#47 Fixed a bug
  server/public/script/sectionsv2.js
Labels: bug

#49 Updating master branch - Artist Page added
  server/public/icons/blackShuffle.svg
  server/public/icons/whiteShuffle.svg
  server/public/stylesheets/v2.css
  server/views/v2.ejs
Labels: enhancement

#51 Updating Master Branch @ Artist Page
  server/public/icons/blackShuffle.svg
  server/public/icons/whiteShuffle.svg
  server/public/script/fetch.js
  server/public/stylesheets/v2.css
  server/views/v2.ejs
Labels: bug

#52 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#57 Updating Master Branch @ Artist Page
  package-lock.json
  package.json
  server/public/script/animationv2.js
  server/public/script/fetch.js
  server/public/script/sectionsv2.js
  server/public/script/util.js
  server/public/stylesheets/v2.css
  server/routes/scraperRoutes.js
  server/server.js
  server/views/v2.ejs
Labels: enhancement, javascript

#60 Updating Master Branch @ ArtistPage w/ Dev #U.50
  server/public/background/black.png
  server/public/icons/x.gif
  server/public/script/fetch.js
  server/public/script/sectionsv2.js
  server/public/stylesheets/v2.css
  server/routes/scraperRoutes.js
  server/views/v2.ejs
Labels: bug, enhancement, javascript

#63 Updating Master Branch w/ Dev
  server/public/background/romanceGenreBG.jpeg
  server/public/script/animationv2.js
  server/public/script/sectionsv2.js
  server/views/v2.ejs
Labels: javascript

#64 Updating Master Branch @ Dev w/ Album && Artist - Page
  server/public/script/animationv2.js
  server/public/script/sectionsv2.js
  server/public/script/util.js
  server/public/stylesheets/v2.css
Labels: enhancement, javascript
